[project]
name = "cloze-wikt-cards"
version = "0.2.0"
description = "Tools for creating and managing cloze flashcards from Wiktionary entries for the Vietnamese language."
readme = "README.md"
authors = [{ name = "Devin Ha", email = "t.ha@tu-berlin.de" }]
requires-python = ">=3.10"
dependencies = [
    "flask==3.1.0",
    "pandas==2.2.3",
    "transformers[torch]==4.50.0",
    "cudf-cu12==25.4.*",
]

[[tool.uv.index]]
name = "nvidia"
url = "https://pypi.nvidia.com"


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = ["ipykernel>=6.29.5"]


[project.scripts]
server = "asr_adder.server.server:main"
fill_with_wikt = "cloze_wikt_cards.wiktionary_defs.fill_with_wikt:main"
fill_examples = "cloze_wikt_cards.anki_examples.fill_examples:main"
merge_tags = "cloze_wikt_cards.anki_utils.merge_tags:main"
